{{- if eq .Values.engine "woocommerce" }}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.mysql.user | default "wordpress" | quote }}
  password: {{ .Values.mysql.password | quote }}
  rootPassword: {{ .Values.mysql.rootPassword | quote }}
{{- end }}

