{{- if eq .Values.engine "medusa" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-stub
  labels:
    app: medusa-stub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa-stub
  template:
    metadata:
      labels:
        app: medusa-stub
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.0
          ports:
            - containerPort: 80
          resources: {{- toYaml .Values.medusaStub.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: medusa-stub
spec:
  type: ClusterIP
  selector:
    app: medusa-stub
  ports:
    - port: 80
      targetPort: 80
{{- end }}